<dec f='linux-4.14.y/include/uapi/linux/kvm.h' l='348' type='struct (anonymous struct at /home/tempdban/kernel/stable/./include/uapi/linux/kvm.h:343:3)'/>
<offset>0</offset>
<doc f='linux-4.14.y/include/uapi/linux/kvm.h' l='342'>/* KVM_EXIT_INTERNAL_ERROR */</doc>
<use f='linux-4.14.y/arch/x86/kvm/vmx.c' l='6147' u='m' c='handle_exception'/>
<use f='linux-4.14.y/arch/x86/kvm/vmx.c' l='6148' u='m' c='handle_exception'/>
<use f='linux-4.14.y/arch/x86/kvm/vmx.c' l='6149' u='m' c='handle_exception'/>
<use f='linux-4.14.y/arch/x86/kvm/vmx.c' l='6150' u='m' c='handle_exception'/>
<use f='linux-4.14.y/arch/x86/kvm/vmx.c' l='6151' u='m' c='handle_exception'/>
<use f='linux-4.14.y/arch/x86/kvm/vmx.c' l='6697' u='m' c='handle_task_switch'/>
<use f='linux-4.14.y/arch/x86/kvm/vmx.c' l='6698' u='m' c='handle_task_switch'/>
<use f='linux-4.14.y/arch/x86/kvm/vmx.c' l='6858' u='m' c='handle_invalid_guest_state'/>
<use f='linux-4.14.y/arch/x86/kvm/vmx.c' l='6859' u='m' c='handle_invalid_guest_state'/>
<use f='linux-4.14.y/arch/x86/kvm/vmx.c' l='8945' u='m' c='vmx_handle_exit'/>
<use f='linux-4.14.y/arch/x86/kvm/vmx.c' l='8946' u='m' c='vmx_handle_exit'/>
<use f='linux-4.14.y/arch/x86/kvm/vmx.c' l='8947' u='m' c='vmx_handle_exit'/>
<use f='linux-4.14.y/arch/x86/kvm/vmx.c' l='8948' u='m' c='vmx_handle_exit'/>
<use f='linux-4.14.y/arch/x86/kvm/vmx.c' l='8949' u='m' c='vmx_handle_exit'/>
<use f='linux-4.14.y/arch/x86/kvm/vmx.c' l='8951' u='m' c='vmx_handle_exit'/>
<use f='linux-4.14.y/arch/x86/kvm/vmx.c' l='8952' u='m' c='vmx_handle_exit'/>
<use f='linux-4.14.y/arch/x86/kvm/x86.c' l='5446' u='m' c='handle_emulation_failure'/>
<use f='linux-4.14.y/arch/x86/kvm/x86.c' l='5447' u='m' c='handle_emulation_failure'/>
