<def f='linux-4.18.y/include/linux/aer.h' l='58' ll='61' type='int pci_cleanup_aer_uncorrect_error_status(struct pci_dev * dev)'/>
<use f='linux-4.18.y/drivers/dma/ioat/init.c' l='1270' u='c' c='ioat_pcie_error_slot_reset'/>
<use f='linux-4.18.y/drivers/net/ethernet/intel/e1000e/netdev.c' l='6857' u='c' c='e1000_io_slot_reset'/>
<use f='linux-4.18.y/drivers/net/ethernet/intel/i40e/i40e_main.c' l='14248' u='c' c='i40e_pci_error_slot_reset'/>
<use f='linux-4.18.y/drivers/net/ethernet/intel/igb/igb_main.c' l='9019' u='c' c='igb_io_slot_reset'/>
<use f='linux-4.18.y/drivers/net/ethernet/intel/ixgbe/ixgbe_main.c' l='10872' u='c' c='ixgbe_io_error_detected'/>
<use f='linux-4.18.y/drivers/net/ethernet/intel/ixgbe/ixgbe_main.c' l='10942' u='c' c='ixgbe_io_slot_reset'/>
<use f='linux-4.18.y/drivers/pci/pcie/err.c' l='255' u='c' c='broadcast_error_message'/>
<use f='linux-4.18.y/drivers/pci/pcie/err.c' l='320' u='c' c='pcie_do_fatal_recovery'/>
<use f='linux-4.18.y/drivers/scsi/mpt3sas/mpt3sas_scsih.c' l='10968' u='c' c='scsih_pci_resume'/>
