<dec f='include/boost/exception/exception.hpp' l='231' type='void boost::exception::~exception()'/>
<def f='include/boost/exception/exception.hpp' l='274' ll='278' type='void boost::exception::~exception()'/>
<ovr f='include/boost/exception/exception.hpp' l='330' c='_ZN5boost16exception_detail19error_info_injectorD1Ev'/>
