<def f='include/boost/exception/exception.hpp' l='423' ll='427' type='void boost::exception_detail::copy_boost_exception(void * , const void * )'/>
