<def f='include/boost/exception/exception.hpp' l='58' ll='62' type='T * boost::exception_detail::refcount_ptr::get() const'/>
<use f='include/boost/exception/exception.hpp' l='415' u='c' c='_ZN5boost16exception_detail20copy_boost_exceptionEPNS_9exceptionEPKS1_'/>
