<def f='include/c++/4.8.2/system_error' l='121' ll='122' type='void std::error_code::error_code(int __v, const std::error_category &amp; __cat)'/>
<use f='include/c++/4.8.2/system_error' l='174' u='c' c='_ZSt15make_error_codeSt4errc'/>
<use f='include/c++/4.8.2/system_error' l='333' u='c' c='_ZNSt12system_errorC1EiRKSt14error_category'/>
<use f='include/c++/4.8.2/system_error' l='334' u='c' c='_ZNSt12system_errorC1EiRKSt14error_category'/>
<use f='include/c++/4.8.2/system_error' l='337' u='c' c='_ZNSt12system_errorC1EiRKSt14error_categoryRKSs'/>
<use f='include/c++/4.8.2/system_error' l='338' u='c' c='_ZNSt12system_errorC1EiRKSt14error_categoryRKSs'/>
<use f='include/c++/4.8.2/future' l='82' u='c' c='_ZSt15make_error_codeSt11future_errc'/>
