<dec f='include/c++/4.8.2/bits/exception_ptr.h' l='92' type='void std::__exception_ptr::exception_ptr::exception_ptr(const std::__exception_ptr::exception_ptr &amp; )'/>
<use f='include/c++/4.8.2/bits/nested_exception.h' l='70' u='c' c='_ZNKSt16nested_exception14rethrow_nestedEv'/>
<use f='include/c++/4.8.2/bits/nested_exception.h' l='74' u='c' c='_ZNKSt16nested_exception10nested_ptrEv'/>
<use f='include/c++/4.8.2/future' l='598' u='c' c='_ZNKSt14__basic_future13_M_get_resultEv'/>
