<inh f='include/boost/exception/exception.hpp' l='208' c='boost::exception'/>
<def f='include/boost/exception/exception.hpp' l='319' ll='333'/>
<fun r='_ZN5boost16exception_detail19error_info_injectorC1ERKT_'/>
<fun r='_ZN5boost16exception_detail19error_info_injectorD1Ev'/>
