<def f='include/boost/exception/exception.hpp' l='391' ll='403'/>
<ovr f='include/boost/exception/exception.hpp' l='431' c='boost::exception_detail::clone_impl'/>
<size>8</size>
<fun r='_ZNK5boost16exception_detail10clone_base5cloneEv'/>
<fun r='_ZNK5boost16exception_detail10clone_base7rethrowEv'/>
<fun r='_ZN5boost16exception_detail10clone_baseD1Ev'/>
