<inh f='include/c++/4.8.2/exception' l='60' c='std::exception'/>
<def f='include/c++/4.8.2/stdexcept' l='55' ll='70'/>
<ovr f='include/c++/4.8.2/stdexcept' l='74' c='std::domain_error'/>
<ovr f='include/c++/4.8.2/stdexcept' l='82' c='std::invalid_argument'/>
<ovr f='include/c++/4.8.2/stdexcept' l='91' c='std::length_error'/>
<ovr f='include/c++/4.8.2/stdexcept' l='100' c='std::out_of_range'/>
<ovr f='include/c++/4.8.2/future' l='93' c='std::future_error'/>
<size>16</size>
<doc f='include/c++/4.8.2/stdexcept' l='50'>/** Logic errors represent problems in the internal logic of a program;
   *  in theory, these are preventable, and even detectable before the
   *  program runs (e.g., violations of class invariants).
   *  @brief One of two subclasses of exception.
   */</doc>
<mbr r='std::logic_error::_M_msg' o='64' t='std::string'/>
<fun r='_ZNSt11logic_errorC1ERKSs'/>
<fun r='_ZNSt11logic_errorD1Ev'/>
<fun r='_ZNKSt11logic_error4whatEv'/>
